runtime: python39
entrypoint: gunicorn -b :$PORT --timeout 120 --workers 2 --threads 4 legal_assistant.wsgi

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6
  max_concurrent_requests: 50

handlers:
- url: /static
  static_dir: staticfiles/
  secure: always

- url: /.*
  script: auto
  secure: always

env_variables:
  DJANGO_SETTINGS_MODULE: "legal_assistant.settings.production"
  DEBUG: "True"
  SECRET_KEY: "django-insecure-o2d6u5@lq4$zdtt%64^w!8i4g6yjb!hqnbt)xaph2u++3$wi2@"
  ANTHROPIC_API_KEY: "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"
  OPENAI_API_KEY: "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"
  DB_NAME: "avocato"
  DB_USER: "postgres"
  DB_PASSWORD: "Born1984!@"
  DB_HOST: "projectschool.postgres.database.azure.com"
  DB_PORT: "5432"
  SERPER_API_KEY: "4fcf1f4b77fa58bb96a0071e2800dbb246e814d6"
  AZURE_STORAGE_ACCOUNT_KEY: "cUfAkCzKvCvVuh1S8L12zHblfbE2wWhHldSUIiEzxHE4y0uD7wraCDxo1RSqFbrcCnbDPRo2VIRE+ASt9FRdwg=="
  AZURE_STORAGE_ACCOUNT_NAME: "greg123"
  AZURE_STORAGE_CONTAINER_NAME: "media"
  AZURE_CLIENT_ID: "68d56521-9298-4434-a3de-2e622651d5af"
  AZURE_CLIENT_SECRET: "IVp8Q~qRxQdQU8.5fqnzkayyRH0lMwD8uPLeqcEy"
  AZURE_TENANT_ID: "6e56df37-ecd4-48e6-b173-cae3280d3f5c"
