# Generated by Django 4.2 on 2024-11-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('analisi_ai', models.TextField(blank=True)),
                ('riferimenti_legali', models.TextField(blank=True)),
                ('stato', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casi',
            },
        ),
    ]
