# Generated by Django 4.2 on 2024-11-23 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_documentaryevidence_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioLegale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Studio')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='studio_logos/')),
                ('indirizzo', models.CharField(max_length=200)),
                ('citta', models.CharField(max_length=100)),
                ('cap', models.CharField(max_length=10)),
                ('provincia', models.CharField(max_length=2)),
                ('paese', models.CharField(default='Italia', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('specializzazioni', models.JSONField(default=list)),
                ('ai_suggestions_enabled', models.BooleanField(default=True, verbose_name='Suggerimenti IA')),
                ('ai_analysis_enabled', models.BooleanField(default=True, verbose_name='Analisi Automatica')),
                ('ai_templates_enabled', models.BooleanField(default=True, verbose_name='Generazione Modelli')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Studio Legale',
                'verbose_name_plural': 'Studi Legali',
            },
        ),
    ]
