# Generated by Django 5.1.4 on 2024-12-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_studiolegale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentaryevidence',
            name='document_file',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
