# Generated by Django 5.1.4 on 2024-12-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_alter_documentaryevidence_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentaryevidence',
            name='document_file',
            field=models.FileField(default=None, upload_to='documentary_evidences/'),
            preserve_default=False,
        ),
    ]
