# Generated by Django 4.2 on 2024-12-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0012_documentaryevidence_extracted_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentaryevidence',
            name='extracted_text',
            field=models.TextField(blank=True, verbose_name='Testo Estratto'),
        ),
    ]
