# Generated by Django 4.2 on 2024-12-31 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0013_alter_documentaryevidence_extracted_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oggetto', models.CharField(max_length=200, verbose_name='Oggetto')),
                ('messaggio', models.TextField(verbose_name='Messaggio')),
                ('data_creazione', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
            },
        ),
    ]
