# Generated by Django 4.2 on 2025-01-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='analisi_legale',
            field=models.TextField(blank=True),
        ),
    ]
