# Generated by Django 4.2 on 2024-11-23 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legal_rag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalcodearticle',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PenalCodeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='legal_rag.penalcodetitle')),
            ],
            options={
                'ordering': ['title', 'number'],
            },
        ),
        migrations.AddField(
            model_name='penalcodearticle',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='legal_rag.penalcodesection'),
        ),
    ]
