# Generated by Django 4.2 on 2024-12-21 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_alter_documentaryevidence_extracted_text'),
        ('legal_rag', '0002_penalcodearticle_description_penalcodesection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_title', models.CharField(max_length=255)),
                ('search_link', models.URLField()),
                ('search_snippet', models.TextField()),
                ('date_saved', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_search_results', to='cases.caso')),
            ],
        ),
    ]
