# Generated by Django 4.2 on 2024-12-25 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0013_alter_documentaryevidence_extracted_text'),
        ('legal_rag', '0004_pdfanalysisresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfanalysisresult',
            name='caso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdf_analyses', to='cases.caso'),
        ),
    ]
