name: Deploy to Azure

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: avocato-fvhmgsdxgtcbdxhz
  PYTHON_VERSION: '3.10'
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  RESOURCE_GROUP: 'assitants'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Required Directories
      run: |
        mkdir -p staticfiles
        mkdir -p media

    - name: Copy Static Assets
      run: |
        cp -r assets/* staticfiles/ || true
        cp -r static/assets/* staticfiles/ || true

    - name: Collect Static Files
      run: python manage.py collectstatic --noinput
      env:
        DJANGO_SETTINGS_MODULE: legal_assistant.settings.production
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: 'False'
        ALLOWED_HOSTS: ${{ env.AZURE_WEBAPP_NAME }}.germanywestcentral-01.azurewebsites.net

    - name: Run Tests
      run: |
        python manage.py test
      env:
        DJANGO_SETTINGS_MODULE: legal_assistant.settings.production
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: 'False'

    - name: Create deployment package
      run: |
        # Ensure all static files are included
        zip -r deployment.zip . -x "*.git*" "*.github*" "*.pytest_cache*" "*.vscode*" "venv/*" "*.pyc"

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deployment.zip

    - name: Post Deployment Status
      run: |
        echo "Deployment completed. Static files should be served from:"
        echo "https://${{ env.AZURE_WEBAPP_NAME }}.germanywestcentral-01.azurewebsites.net/assets/"
