name: Build and Collect Static

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create staticfiles directory
      run: mkdir -p staticfiles
        
    - name: Copy assets
      run: cp -r assets/* staticfiles/ || true
        
    - name: Collect Static Files
      env:
        DJANGO_SETTINGS_MODULE: legal_assistant.settings.production
      run: python manage.py collectstatic --noinput
